//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vrossi.ScaffoldCore.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vrossi.ScaffoldCore.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html
        ///          PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///      xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta name=x-apple-disable-message-reformatting /&gt;
        ///    &lt;meta http-equiv=X-UA-Compatible /&gt;
        ///    &lt;meta charset=utf-8 /&gt;
        ///    &lt;meta name=viewport content=target-densitydpi =device-dpi /&gt;
        ///    &lt;meta content=true na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultEmailTemplate {
            get {
                return ResourceManager.GetString("DefaultEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html
        ///          PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///      xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta name=x-apple-disable-message-reformatting /&gt;
        ///    &lt;meta http-equiv=X-UA-Compatible /&gt;
        ///    &lt;meta charset=utf-8 /&gt;
        ///    &lt;meta name=viewport content=target-densitydpi =device-dpi /&gt;
        ///    &lt;meta content=true na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultEmailTemplateWithoutButton {
            get {
                return ResourceManager.GetString("DefaultEmailTemplateWithoutButton", resourceCulture);
            }
        }
    }
}
